//USERS
export const REGISTER = "REGISTER";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";

//SERVICES
export const GET_SERVICES = "GET_SERVICES";
export const CREATE_SERVICE = "CREATE_SERVICE";
export const EDIT_SERVICE = "EDIT_SERVICE";
export const DELETE_SERVICE = "DELETE_SERVICE";

//DISABLED DATES
export const GET_DISABLED_DATES = "GET_DISABLED_DATES";
export const DISABLE_DATE = "DISABLE_DATE";
export const CANCEL_DISABLE_DATE = "CANCEL_DISABLE_DATE";

//RESERVATIONS
export const GET_AVAILABLE_TIMES = "GET_AVAILABLE_TIMES";
export const GET_ALL_RESERVATIONS = "GET_ALL_RESERVATIONS";
export const GET_RESERVATIONS_BY_DATE = "GET_RESERVATIONS_BY_DATE";
export const GET_RESERVATIONS_BY_MAIL = "GET_RESERVATIONS_BY_MAIL";
export const NEW_RESERVATION = "NEW_RESERVATION";
export const SEND_CANCEL_RESERVATION = "SEND_CANCEL_RESERVATION";
export const CONFIRM_CANCEL_RESERVATION = "CONFIRM_CANCEL_RESERVATION";
export const UPDATE_STATE_RESERVATION = "UPDATE_STATE_RESERVATION";
